### ISSUE TITLE
Add shoulda-matchers support

### ISSUE THREAD

**Issue by bunnymatic** [carbonfive/raygun#125]
Shoulda Matchers would be a nice addition.  Tests for AR model settings can be written really cleanly.  

Instead of writing a test like

```
describe MyThing do
   let(:name) { 'valid' }
   subject(:my_thing) { FactoryGirl.build(:my_thing, :short_name => name)
   it { should be_valid? }
   context 'if the name is too long" do
      let(:name) { 'a' * 257 }
      it { should_not be_valid? }
   end
```

   end

you can write it like this          

```
describe MyThing do
   it { should ensure_length_of(:short_name).is_at_most(256) }
end
```

Other really helpful matchers:

```
it { should validate_uniqueness_of(:the_uniq_field) }
it { should validate_presence_of(:the_uniq_field) }
it { should validate_numericality_of(:integer_field).only_integer }
it { should validate_numericality_of(:numeric_field) }

it { should belong_to(:parent) }
it { should have_many(:kids) }
```

There are lots more. 

Sadly, the `shoulda` team is working on an issue with running under rails4.1.0beta so for now, i'm filing this as a PR that would be great, once the `shoulda-matchers` gem is ready for rails 4.1.0

**Comment by bunnymatic** [comment]
This is pretty stale.  We can probably live without this gem addition.

**Comment by mattbrictson** [comment]
FWIW we are using `shoulda-matchers` on my current project (Rails 6) and it is working nicely for model validations tests.

**Comment by bunnymatic** [comment]
I agree @mattbrictson.  I still like it as a gem.  Is it worth trying to make a case for getting it in raygun?

**Comment by mattbrictson** [comment]
I'll vouch for it! I think we can get it in.

**Comment by mattbrictson** [comment]
Can you open a PR?

**Comment by bunnymatic** [comment]
will do

**Comment by bunnymatic** [comment]
PR here.  https://github.com/carbonfive/raygun-rails/pull/284

Since this add is in a different repo, I guess we can close this ticket when this is merged in... right?

**Comment by mattbrictson** [comment]
Closed via https://github.com/carbonfive/raygun-rails/pull/284
