### ISSUE TITLE
Jasmine-Rails tests fail out of the box

### ISSUE THREAD

**Issue by bunnymatic** [carbonfive/raygun#130]
On a brand new project from raygun, upgraded to ruby 2.2.2 and ran the specs and got this Jasmine failure.

 <div class='top'>
        <header class="exception">
            <h2><strong>Sprockets::Rails::Helper::AbsoluteAssetPathError</strong> <span>at /</span></h2>
            <p>Asset names passed to helpers should not include the &quot;/assets/&quot; prefix. Instead of &quot;/assets/jasmine.self.css&quot;, use &quot;jasmine.self.css&quot;</p>
        </header>
    </div>

Here's a bit of the backtrace

<div class="name">
 <strong>#&lt;Class:0x007f893e45fb18&gt;</strong><span class='method'>#check_errors_for</span>
 <span class="filename">sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb</span>, line <span class="line">200</span>
</div>
 <div class="name">
 <strong>#&lt;Class:0x007f893e45fb18&gt;</strong><span class='method'>#asset_path</span>
 <span class="filename">sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb</span>, line <span class="line">89</span>
 </div>
 <div class="name">
 <strong>#&lt;Class:0x007f893e45fb18&gt;</strong><span class='method'>#stylesheet_path</span>
 <span class="filename">actionview (4.2.1) lib/action_view/helpers/asset_url_helper.rb</span>, line <span class="line">267</span>
  </div>

More as i try to debug, but I may move to Karma instead.

Also, looks like it's only the commandline tests.  If you run the app and hit the `/specs` endpoint, everyone is happy.

**Comment by christiannelson** [comment]
Thanks for logging this, it's a pain for sure.

This should be logged in the http://github.com/carbonfive/raygun-rails repo and it's a dup: https://github.com/carbonfive/raygun-rails/issues/48

Rudy, has a PR into jasmine-rails that fixes this problem.

**Comment by bunnymatic** [comment]
whoops.  thanks for the clarification.  and sorry for the dup.  i should
have known that raygun-rails was the right place to check.

**Comment by christiannelson** [comment]
Nah, it's totally okay. I'm PSYCHED you log things!!! :)
