### ISSUE TITLE
autoprefixer

### ISSUE THREAD

**Issue by keathley** [carbonfive/raygun#131]
What do y'all think about adding something like https://github.com/ai/autoprefixer-rails? I'm using it on two different Raygun generated apps and it's been working great. Takes a lot of the pain out of vendor prefixing without needing a set or sass mixins or similar solution. If it's something thats worth pursuing then I'm happy to submit a PR.

**Comment by wless1** [comment]
:+1:

**Comment by christiannelson** [comment]
See https://github.com/carbonfive/raygun-rails/issues/51.
