### ISSUE TITLE
Environment flag to make tests run in a browser in the foreground

### ISSUE THREAD

**Issue by clarkcutler** [carbonfive/raygun#139]
On some projects, I've had a flag to make feature specs run in the browser. Which can be handy when debugging. Usage looks like, for example:
```
CHROME=true rspec <path>
```

@christiannelson Does this sound like something we'd like to add to Raygun? If so I can put up a PR.

**Comment by eskfung** [comment]
This was added in https://github.com/carbonfive/raygun-rails/pull/121
