### ISSUE TITLE
Fragile connection to rubocop.yml with `carbonfive/c5-conventions`

### ISSUE THREAD

**Issue by bunnymatic** [carbonfive/raygun#146]
Our connection to the `rubocop.yml` file in https://github.com/carbonfive/c5-conventions seems fragile.

Updates to that repo will affect all consumers out in the world (who we don't know) and may cause issues with their app.  We've already seen it affect 1 client project in house.

Could we think about copying this file (instead of linking) so that at the time the app is generated, we get the current state of c5-conventions, but it is not live updated.  

If we want more functionality, I could see a rake task (or something) that would pull the latest version.  

I could imagine the rubocop being included with some very simple gemfile so it could be versioned and managed with all our other dependencies but that might not be worth the effort of managing a gem.  So I propose the above (agile) solution.

Thoughts?

**Comment by mattbrictson** [comment]
> Could we think about copying this file (instead of linking) so that at the time the app is generated, we get the current state of c5-conventions, but it is not live updated.

💯 

The generated `.rubocop.yml` could have a header like this:

```yaml
# Sourced from carbonfive/c5-conventions @ 9b747be.
# If you make changes to this file, consider opening a PR to backport them to the c5-conventions repo:
# https://github.com/carbonfive/c5-conventions/blob/master/rubocop/rubocop.yml
```

That way we remove the brittle dependency but still encourage the conventions to be updated for the benefit of future projects.

For C5 internal tools, I can see there is an argument to keep the RuboCop configs for these projects tightly coupled to the conventions, so that they are always consistent. But that can be the exception to the rule. For new projects generated from raygun, I prefer the copy-not-link solution.

**Comment by bunnymatic** [comment]
As I look at `raygun` I suppose this could be done by using different `raygun-rails` templates, though it seems pretty nuts to have 2 full rails repos to manage where the only difference is 3 lines in the `.rubocop.yml` file. 

I'll look into pulling a static version and we can see how that looks.

It could be a raygun option to use the linked version vs the static version.  That might answer the question for internal C5 tools/apps.

**Comment by mattbrictson** [comment]
To clarify: I mean that since our internal apps have already been generated and have links to c5-conventions, they can be left as-is. All future apps generated from raygun can use the static approach. I don't think we need to parameterize linked vs static for future projects generated from raygun.
